CREATE TABLE `feature_access_control` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`canViewDashboard` boolean NOT NULL DEFAULT true,
	`canViewActiveSessions` boolean NOT NULL DEFAULT true,
	`canViewRadiusLogs` boolean NOT NULL DEFAULT false,
	`canViewNasHealth` boolean NOT NULL DEFAULT true,
	`canManageNas` boolean NOT NULL DEFAULT true,
	`canViewVpn` boolean NOT NULL DEFAULT false,
	`canManageMikrotik` boolean NOT NULL DEFAULT true,
	`canManageSubscribers` boolean NOT NULL DEFAULT true,
	`canViewClients` boolean NOT NULL DEFAULT false,
	`canManagePlans` boolean NOT NULL DEFAULT true,
	`canAccessRadiusControl` boolean NOT NULL DEFAULT false,
	`canManageCards` boolean NOT NULL DEFAULT true,
	`canPrintCards` boolean NOT NULL DEFAULT true,
	`canViewWallet` boolean NOT NULL DEFAULT true,
	`canViewInvoices` boolean NOT NULL DEFAULT true,
	`canViewSubscriptions` boolean NOT NULL DEFAULT true,
	`canViewBillingDashboard` boolean NOT NULL DEFAULT false,
	`canViewSaasPlans` boolean NOT NULL DEFAULT false,
	`canViewReports` boolean NOT NULL DEFAULT true,
	`canViewBandwidthAnalytics` boolean NOT NULL DEFAULT true,
	`canViewSettings` boolean NOT NULL DEFAULT true,
	`canViewAuditLog` boolean NOT NULL DEFAULT false,
	`canAccessSupport` boolean NOT NULL DEFAULT true,
	`canManageSms` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `feature_access_control_id` PRIMARY KEY(`id`),
	CONSTRAINT `feature_access_control_userId_unique` UNIQUE(`userId`)
);
