CREATE TABLE `site_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`siteName` varchar(100) NOT NULL DEFAULT 'Radius Pro',
	`siteNameAr` varchar(100) DEFAULT 'راديوس برو',
	`tagline` text DEFAULT ('Professional RADIUS Management Platform'),
	`taglineAr` text DEFAULT ('منصة RADIUS احترافية لإدارة الإنترنت والكروت'),
	`logoUrl` text,
	`faviconUrl` text,
	`heroTitle` text DEFAULT ('Complete SaaS System'),
	`heroTitleAr` text DEFAULT ('نظام SaaS متكامل'),
	`heroSubtitle` text DEFAULT ('Professional RADIUS platform for Internet and card management'),
	`heroSubtitleAr` text DEFAULT ('منصة RADIUS احترافية لإدارة الإنترنت والكروت'),
	`heroDescription` text DEFAULT ('Complete SaaS system for managing Internet networks with MikroTik
Fast • Secure • Scalable'),
	`heroDescriptionAr` text DEFAULT ('نظام SaaS متكامل لإدارة شبكات الإنترنت مع MikroTik
سريع • آمن • قابل للتوسع'),
	`uptimePercent` varchar(10) DEFAULT '99.9%',
	`activeClients` varchar(20) DEFAULT '+1000',
	`managedCards` varchar(20) DEFAULT '+50K',
	`supportHours` varchar(20) DEFAULT '24/7',
	`supportEmail` varchar(320) DEFAULT 'support@radius-pro.com',
	`supportPhone` varchar(50) DEFAULT '+970 59 XXX XXXX',
	`supportHoursText` text DEFAULT ('Saturday - Thursday: 9 AM - 6 PM'),
	`supportHoursTextAr` text DEFAULT ('السبت - الخميس: 9 صباحاً - 6 مساءً'),
	`companyName` varchar(255) DEFAULT 'RadiusPro',
	`companyNameAr` varchar(255) DEFAULT 'راديوس برو',
	`copyrightText` text DEFAULT ('© 2026 RadiusPro. All rights reserved.'),
	`copyrightTextAr` text DEFAULT ('جميع الحقوق محفوظة. RadiusPro 2026 ©'),
	`facebookUrl` text,
	`twitterUrl` text,
	`linkedinUrl` text,
	`instagramUrl` text,
	`metaTitle` text DEFAULT ('Radius Pro - Professional RADIUS Management'),
	`metaTitleAr` text DEFAULT ('راديوس برو - إدارة RADIUS احترافية'),
	`metaDescription` text,
	`metaDescriptionAr` text,
	`metaKeywords` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `site_settings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `subscription_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`nameAr` varchar(100) NOT NULL,
	`description` text,
	`descriptionAr` text,
	`price` decimal(10,2) NOT NULL,
	`currency` varchar(3) NOT NULL DEFAULT 'USD',
	`billingPeriod` enum('monthly','yearly') NOT NULL DEFAULT 'monthly',
	`features` json NOT NULL,
	`featuresAr` json NOT NULL,
	`maxCards` int,
	`maxNasDevices` int,
	`maxResellers` int,
	`isPopular` boolean NOT NULL DEFAULT false,
	`displayOrder` int NOT NULL DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `subscription_plans_id` PRIMARY KEY(`id`)
);
