#!/bin/bash
#===============================================================================
# PPTP VPN Server Installation Script
# For RADIUS SaaS Platform
#
# This script installs and configures a PPTP VPN server that allows
# MikroTik routers to connect to your RADIUS server through a secure tunnel.
#
# Usage: sudo bash install-vpn.sh
#===============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

#===============================================================================
# CONFIGURATION - MODIFY THESE VALUES
#===============================================================================

# VPN Server IP (the IP that will be assigned to the server inside VPN)
VPN_SERVER_IP="10.0.0.1"

# VPN Client IP Range (IPs assigned to connecting MikroTik routers)
VPN_CLIENT_START="10.0.0.100"
VPN_CLIENT_END="10.0.0.200"

# DNS Servers for VPN clients
DNS_PRIMARY="8.8.8.8"
DNS_SECONDARY="8.8.4.4"

# Network interface (usually eth0 or ens3)
NETWORK_INTERFACE="eth0"

#===============================================================================

print_step() {
    echo -e "${GREEN}[STEP]${NC} $1"
}

print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check root
if [ "$EUID" -ne 0 ]; then
    print_error "Please run as root (sudo bash install-vpn.sh)"
    exit 1
fi

echo -e "${BLUE}"
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║              PPTP VPN Server Installation                        ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Detect network interface
detect_interface() {
    print_step "Detecting network interface..."
    
    # Try to find the main interface
    DETECTED_IF=$(ip route | grep default | awk '{print $5}' | head -1)
    
    if [ -n "$DETECTED_IF" ]; then
        NETWORK_INTERFACE=$DETECTED_IF
        print_info "Detected interface: $NETWORK_INTERFACE"
    else
        print_info "Using default interface: $NETWORK_INTERFACE"
    fi
}

# Install PPTP
install_pptp() {
    print_step "Installing PPTP server..."
    
    apt-get update -y
    apt-get install -y pptpd iptables-persistent
    
    print_success "PPTP installed"
}

# Configure PPTP
configure_pptp() {
    print_step "Configuring PPTP..."
    
    # Backup original config
    cp /etc/pptpd.conf /etc/pptpd.conf.backup 2>/dev/null || true
    
    # Create pptpd.conf
    cat > /etc/pptpd.conf << EOF
# PPTP Server Configuration
# Generated by RADIUS SaaS VPN Installer

option /etc/ppp/pptpd-options
logwtmp

# Server IP inside VPN tunnel
localip ${VPN_SERVER_IP}

# Client IP range
remoteip ${VPN_CLIENT_START}-${VPN_CLIENT_END##*.}

# Enable broadcast relay
bcrelay eth0
EOF
    
    print_success "pptpd.conf configured"
}

# Configure PPP options
configure_ppp_options() {
    print_step "Configuring PPP options..."
    
    cat > /etc/ppp/pptpd-options << EOF
# PPP Options for PPTP
# Generated by RADIUS SaaS VPN Installer

name pptpd

# Authentication methods
# Refuse insecure methods
refuse-pap
refuse-chap
refuse-mschap

# Require MS-CHAPv2 (secure)
require-mschap-v2

# Require MPPE encryption
require-mppe-128

# DNS servers for clients
ms-dns ${DNS_PRIMARY}
ms-dns ${DNS_SECONDARY}

# Network settings
proxyarp
nodefaultroute

# Logging
debug
dump
lock

# Disable compression (better compatibility)
nobsdcomp
novj
novjccomp
nologfd

# MTU/MRU settings
mtu 1400
mru 1400
EOF
    
    print_success "PPP options configured"
}

# Enable IP forwarding
enable_forwarding() {
    print_step "Enabling IP forwarding..."
    
    # Enable immediately
    echo 1 > /proc/sys/net/ipv4/ip_forward
    
    # Make permanent
    if ! grep -q "net.ipv4.ip_forward=1" /etc/sysctl.conf; then
        echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
    fi
    
    sysctl -p
    
    print_success "IP forwarding enabled"
}

# Configure iptables
configure_iptables() {
    print_step "Configuring iptables..."
    
    # Clear existing rules for VPN
    iptables -t nat -D POSTROUTING -o $NETWORK_INTERFACE -j MASQUERADE 2>/dev/null || true
    
    # NAT for VPN clients
    iptables -t nat -A POSTROUTING -o $NETWORK_INTERFACE -j MASQUERADE
    
    # Allow forwarding for VPN
    iptables -A FORWARD -i ppp+ -o $NETWORK_INTERFACE -j ACCEPT
    iptables -A FORWARD -i $NETWORK_INTERFACE -o ppp+ -m state --state RELATED,ESTABLISHED -j ACCEPT
    
    # Allow GRE protocol (required for PPTP)
    iptables -A INPUT -p gre -j ACCEPT
    iptables -A OUTPUT -p gre -j ACCEPT
    
    # Allow PPTP port
    iptables -A INPUT -p tcp --dport 1723 -j ACCEPT
    
    # Save rules
    netfilter-persistent save
    
    print_success "iptables configured"
}

# Create VPN user management script
create_user_script() {
    print_step "Creating user management scripts..."
    
    # Add user script
    cat > /usr/local/bin/vpn-add-user << 'SCRIPT'
#!/bin/bash
# Add VPN User
# Usage: vpn-add-user <username> <password>

if [ $# -lt 2 ]; then
    echo "Usage: vpn-add-user <username> <password>"
    exit 1
fi

USERNAME=$1
PASSWORD=$2

# Check if user already exists
if grep -q "^$USERNAME " /etc/ppp/chap-secrets; then
    echo "User $USERNAME already exists!"
    exit 1
fi

# Add user
echo "$USERNAME pptpd $PASSWORD *" >> /etc/ppp/chap-secrets

echo "VPN user '$USERNAME' added successfully!"
echo ""
echo "MikroTik PPTP Client Configuration:"
echo "  Server: $(curl -s ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')"
echo "  Username: $USERNAME"
echo "  Password: $PASSWORD"
SCRIPT
    chmod +x /usr/local/bin/vpn-add-user
    
    # Delete user script
    cat > /usr/local/bin/vpn-del-user << 'SCRIPT'
#!/bin/bash
# Delete VPN User
# Usage: vpn-del-user <username>

if [ $# -lt 1 ]; then
    echo "Usage: vpn-del-user <username>"
    exit 1
fi

USERNAME=$1

# Remove user
sed -i "/^$USERNAME /d" /etc/ppp/chap-secrets

echo "VPN user '$USERNAME' deleted!"
SCRIPT
    chmod +x /usr/local/bin/vpn-del-user
    
    # List users script
    cat > /usr/local/bin/vpn-list-users << 'SCRIPT'
#!/bin/bash
# List VPN Users

echo "=== VPN Users ==="
echo ""
printf "%-20s %-20s\n" "Username" "Password"
echo "----------------------------------------"

while IFS=' ' read -r user server pass ip; do
    if [ "$server" = "pptpd" ]; then
        printf "%-20s %-20s\n" "$user" "$pass"
    fi
done < /etc/ppp/chap-secrets

echo ""
echo "Total users: $(grep -c "pptpd" /etc/ppp/chap-secrets 2>/dev/null || echo 0)"
SCRIPT
    chmod +x /usr/local/bin/vpn-list-users
    
    # Status script
    cat > /usr/local/bin/vpn-status << 'SCRIPT'
#!/bin/bash
# VPN Server Status

echo "=== VPN Server Status ==="
echo ""

# Service status
echo "Service Status:"
systemctl status pptpd --no-pager | head -5

echo ""
echo "Active Connections:"
if [ -d /var/run/pptpd ]; then
    ls -la /var/run/pptpd/ 2>/dev/null || echo "No active connections"
else
    echo "No active connections"
fi

echo ""
echo "Connected Clients:"
ip addr show | grep -E "ppp[0-9]+" | awk '{print $2}' || echo "None"

echo ""
echo "Server IP: $(curl -s ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')"
echo "VPN Local IP: 10.0.0.1"
SCRIPT
    chmod +x /usr/local/bin/vpn-status
    
    print_success "User management scripts created"
}

# Start services
start_services() {
    print_step "Starting VPN service..."
    
    systemctl enable pptpd
    systemctl restart pptpd
    
    sleep 2
    
    if systemctl is-active --quiet pptpd; then
        print_success "VPN service started successfully"
    else
        print_error "VPN service failed to start. Check: journalctl -u pptpd"
        exit 1
    fi
}

# Create initial VPN user for MikroTik
create_initial_user() {
    print_step "Creating initial VPN user..."
    
    # Generate random password
    INITIAL_USER="mikrotik"
    INITIAL_PASS=$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | head -c 12)
    
    # Create user
    echo "$INITIAL_USER pptpd $INITIAL_PASS *" > /etc/ppp/chap-secrets
    
    print_success "Initial VPN user created"
    
    # Store credentials for display
    echo "$INITIAL_USER:$INITIAL_PASS" > /root/.vpn_initial_user
    chmod 600 /root/.vpn_initial_user
}

# Print final instructions
print_instructions() {
    SERVER_IP=$(curl -s ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')
    
    # Read initial credentials
    if [ -f /root/.vpn_initial_user ]; then
        INITIAL_USER=$(cut -d: -f1 /root/.vpn_initial_user)
        INITIAL_PASS=$(cut -d: -f2 /root/.vpn_initial_user)
    fi
    
    echo ""
    echo -e "${GREEN}"
    echo "╔══════════════════════════════════════════════════════════════════╗"
    echo "║              VPN Server Installation Complete!                   ║"
    echo "╚══════════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    
    echo ""
    echo "=== VPN Server Information ==="
    echo "Server IP:        $SERVER_IP"
    echo "VPN Type:         PPTP"
    echo "VPN Port:         1723/tcp"
    echo "VPN Local IP:     ${VPN_SERVER_IP}"
    echo "Client IP Range:  ${VPN_CLIENT_START} - ${VPN_CLIENT_END}"
    
    echo ""
    echo "=== Initial VPN User ==="
    echo "Username: $INITIAL_USER"
    echo "Password: $INITIAL_PASS"
    
    echo ""
    echo "=== MikroTik PPTP Client Configuration ==="
    echo "Run these commands on your MikroTik router:"
    echo ""
    echo "/interface pptp-client add name=vpn-radius connect-to=$SERVER_IP user=$INITIAL_USER password=$INITIAL_PASS disabled=no"
    echo ""
    echo "After VPN connects, use ${VPN_SERVER_IP} as RADIUS server address."
    
    echo ""
    echo "=== Management Commands ==="
    echo "Add VPN user:     vpn-add-user <username> <password>"
    echo "Delete VPN user:  vpn-del-user <username>"
    echo "List VPN users:   vpn-list-users"
    echo "Check status:     vpn-status"
    
    echo ""
    echo -e "${YELLOW}IMPORTANT: Save the VPN credentials above!${NC}"
    echo ""
}

# Main
main() {
    detect_interface
    install_pptp
    configure_pptp
    configure_ppp_options
    enable_forwarding
    configure_iptables
    create_user_script
    create_initial_user
    start_services
    print_instructions
}

main "$@"
